org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft & NeoForge
minecraft_version=1.21.1
neo_version=21.1.221
neo_version_range=[21.1.221,)
loader_version_range=[4,)

# Mappings
mapping_channel=official
mapping_version=1.21.1

# Mod Info
mod_id=rsgauges
mod_name=Gauges and Switches
mod_license=MIT
mod_version=1.2.22
mod_group_id=wile.rsgauges
mod_authors=stfwi
mod_description=Ported to NeoForge 1.21.1 with Java 25